### ISSUE TITLE
'qInfo' was not declared in this scope

### ISSUE THREAD

**Issue by JYang25** [schrodinger/gpusimilarity#16]
Hello,

We are trying to install the gpusimilarity on a Centos 6 machine. We followed these steps:

From parent directory of source:
mkdir bld
cd bld
ccmake ../gpusimilarity
make -j5
ctest

When we do "make -j5", an error occurred with this error message, "'qInfo' was not declared in this scope". We tried many ways to solve the problem but failed. Do you have any suggestion?

Thanks

**Comment by lorton** [comment]
@JYang25 - this is a [QT <5.5 issue](https://github.com/mattanger/ckb-next/issues/181).  I'll check in a fix in the next few hours so it'll work with earlier QTs.

**Comment by JYang25** [comment]
@lorton Thank you so much!

**Comment by lorton** [comment]
@JYang25 - can you try pulling down branch 'qinfo' and verifying that it fixes your problem?
