### ISSUE TITLE
error in make

### ISSUE THREAD

**Issue by JYang25** [schrodinger/gpusimilarity#19]
Hello Iorton,

I am following the instructions to build gpusimilarity. Everything seems fine until the last step. When I ran make -j5, I got the following error messgae:

[ 11%] Building CXX object CMakeFiles/fastsim.dir/fastsim.cpp.o
[ 22%] Building CUDA object CMakeFiles/fastsim.dir/fingerprintdb_cuda.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[ 33%] Linking CXX static library libfastsim.a
[ 33%] Built target fastsim
[ 44%] Building CXX object CMakeFiles/fastsimserver.dir/main.cpp.o
[ 55%] Linking CUDA device code CMakeFiles/fastsimserver.dir/cmake_device_link.o
[ 66%] Linking CXX executable fastsimserver
/home/jizhou/install/anaconda/lib/libQt5Core.so.5.9.5: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
/home/jizhou/install/anaconda/lib/libQt5Network.so.5.9.5: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
/home/jizhou/install/anaconda/lib/libQt5Network.so.5.9.5: undefined reference to `operator delete[](void*, unsigned long)@CXXABI_1.3.9'
collect2: error: ld returned 1 exit status
make[2]: *** [fastsimserver] Error 1
make[1]: *** [CMakeFiles/fastsimserver.dir/all] Error 2
make: *** [all] Error 2

I did some research on this, but not able to find the solution. Do you have any suggestion?

Thanks

**Comment by lorton** [comment]
Hi @JYang25 - it looks like a conda / OS error with missing CXXABI support.  Looking at [this conda post](https://github.com/ContinuumIO/anaconda-issues/issues/5191) it's expected that conda now supports the correct CXXABI, is there any chance your conda is out of date?  Are you intending to build this using Conda?

**Comment by JYang25** [comment]
Hi @lorton 

Thanks for the reply! 

I am following these instructions to build gpusimilarity.

> From parent directory of source:
mkdir bld
cd bld
ccmake ../gpusimilarity
make -j5
ctest

The versions of my platform and tools are as follows:

> Operating System  Centos 6
C++/gcc  gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
cmake/ccmake  version 3.12.0
boost  version 1.64


I will read the post about CXXABI. 

Thanks

**Comment by lorton** [comment]
Hi @JYang25 - that version of GCC may be too old...I'm using C++11 and new Cuda functionality - that said your current error doesn't appear to be because of that.  It looks like your libstdc++ is too old, which is likely because of CentOS6.  CentOS6 is pretty old at this point (it's last full update was May 2010).  You may need to update your libstdc++.  If we can figure out the cause, I can add it to a cmake requirement.
