### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by poganyp** [schrodinger/gpusimilarity#42]
I have tried to install this tool and failed. I have rebuilt all the dependencies successfully but failed again:
Installed so far:
gcc-8.1.0
Python 3.7.0 with numpy, sip, pyqt5, rapidjson, simplejson
cmake-3.12.2
boost 1.67.0
cairo1.15.12
non-python linked rapidjson1.1.0
non-python linked eigen3.3
rdkit
Qt5.10.1
And
/home/user/progs/cmake/bld/bin/ccmake \
-DCMAKE_INSTALL_PREFIX:PATH=/home/user/progs/gpusimilarity/bld \
-DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc \
-DBoost_DIR=/home/user/progs/boost/boost \
-DBoost_INCLUDE_DIR=/home/user/progs/boost/boost \
-DBoost_LIBRARY_DIR_DEBUG=/home/user/progs/boost/boost/stage/lib \
-DBoost_LIBRARY_DIR_RELEASE=/home/user/progs/boost/boost/stage/lib \
-DBoost_UNIT_TEST_FRAMEWORK_LIBR=/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so \
-DSLURM_SBATCH_COMMAND=/usr/local/slurm/bin/sbatch \
-DSLURM_SRUN_COMMAND=/usr/local/slurm/bin/srun \
-DCMAKE_CXX_COMPILER=/home/user/progs/gcc/bld/bin/g++ \
-DCMAKE_CXX_COMPILER_AR=/home/user/progs/gcc/bld/bin/gcc-ar \
-DCMAKE_CXX_COMPILER_RANLIB=/home/user/progs/gcc/bld/bin/gcc-ranlib \
-DQt5Core_DIR=/home/user/progs/qt5/bld/lib/cmake/Qt5Core \
-DQt5Network_DIR=/home/user/progs/qt5/bld/lib/cmake/Qt5Network \
-DQt5Concurrent_DIR=/home/user/progs/qt5/bld/lib/cmake/Qt5Concurrent \
/home/user/progs/gpusimilarity/
ccmake finished successfully.
When typing: make
[ 45%] Built target gpusim
[ 54%] Linking CXX executable gpusimserver
libgpusim.a(gpusim.cpp.o): In function `gpusim::GPUSimServer::GPUSimServer(QStringList const&, int)':
gpusim.cpp:(.text+0x88f): undefined reference to `std::invalid_argument::invalid_argument(char const*)'
libgpusim.a(gpusim.cpp.o): In function `gpusim::GPUSimServer::extractData(QString const&, int&, int&, std::vector<std::vector<char, std::allocator<char> >, std::allocator<std::vector<char, std::allocator<char> > > >&, std::vector<char*, std::allocator<char*> >&, std::vector<char*, std::allocator<char*> >&)':
gpusim.cpp:(.text+0xe04): undefined reference to `std::runtime_error::runtime_error(char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [gpusimserver] Error 1
make[1]: *** [CMakeFiles/gpusimserver.dir/all] Error 2
make: *** [all] Error 2

When typing make -j5:
[ 63%] Linking CXX executable test_gpusim
CMakeFiles/test_gpusim.dir/test_gpusim.cpp.o: In function `boost::basic_wrap_stringstream<char>::basic_wrap_stringstream()':
test_gpusim.cpp:(.text._ZN5boost23basic_wrap_stringstreamIcEC2Ev[_ZN5boost23basic_wrap_stringstreamIcEC5Ev]+0x19): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream(std::_Ios_Openmode)'
test_gpusim.cpp:(.text._ZN5boost23basic_wrap_stringstreamIcEC2Ev[_ZN5boost23basic_wrap_stringstreamIcEC5Ev]+0x2b): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
...

Can you suggest me something what should I do?

Best regards,

Peter Pogany

**Comment by lorton** [comment]
It looks like it doesn't like std::runtime_error(const char*) -- that should be used to automatically create an std::string, which is what it takes.  Could you try editing that line in the code to instantiate a string out of the const char* before passing it into the runtime_error and seeing if that helps at all?

**Comment by poganyp** [comment]
That solved this issue, however, I am still having an issue with boost, which I recompiled with gcc-8.1.0. I'll try a newer version of boost.

**Comment by lorton** [comment]
I'd guess boost is the same problem, some char* (not) being implicitly cast to string as I'd expect.  I'm still kind of baffled why you're hitting this...do you have your own CFLAGS or CXXFLAGS defined somehow?

**Comment by poganyp** [comment]
Even with boost version 1.68.0 I go the following messages after doing make -j5:
I have built boost 1.68.0 on gcc-8.1.0. And no other tool had issue with this (e.g. succesful rdkit installation). Do you have any idea what could be the issue?

[100%] Linking CXX executable test_gpusim
CMakeFiles/test_gpusim.dir/test_gpusim.cpp.o: In function `boost::basic_wrap_stringstream<char>::basic_wrap_stringstream()':
test_gpusim.cpp:(.text._ZN5boost23basic_wrap_stringstreamIcEC2Ev[_ZN5boost23basic_wrap_stringstreamIcEC5Ev]+0x19): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream(std::_Ios_Openmode)'
test_gpusim.cpp:(.text._ZN5boost23basic_wrap_stringstreamIcEC2Ev[_ZN5boost23basic_wrap_stringstreamIcEC5Ev]+0x2b): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string()'
CMakeFiles/test_gpusim.dir/test_gpusim.cpp.o: In function `boost::unit_test::make_test_case(boost::function<void ()> const&, boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long)':
test_gpusim.cpp:(.text._ZN5boost9unit_test14make_test_caseERKNS_8functionIFvvEEENS0_13basic_cstringIKcEES8_m[_ZN5boost9unit_test14make_test_caseERKNS_8functionIFvvEEENS0_13basic_cstringIKcEES8_m]+0xae): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
test_gpusim.cpp:(.text._ZN5boost9unit_test14make_test_caseERKNS_8functionIFvvEEENS0_13basic_cstringIKcEES8_m[_ZN5boost9unit_test14make_test_caseERKNS_8functionIFvvEEENS0_13basic_cstringIKcEES8_m]+0xd2): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
CMakeFiles/test_gpusim.dir/test_gpusim.cpp.o: In function `boost::basic_wrap_stringstream<char>::~basic_wrap_stringstream()':
test_gpusim.cpp:(.text._ZN5boost23basic_wrap_stringstreamIcED2Ev[_ZN5boost23basic_wrap_stringstreamIcED5Ev]+0x1a): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
test_gpusim.cpp:(.text._ZN5boost23basic_wrap_stringstreamIcED2Ev[_ZN5boost23basic_wrap_stringstreamIcED5Ev]+0x26): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()'
CMakeFiles/test_gpusim.dir/test_gpusim.cpp.o: In function `boost::basic_wrap_stringstream<char>::str[abi:cxx11]()':
test_gpusim.cpp:(.text._ZN5boost23basic_wrap_stringstreamIcE3strB5cxx11Ev[_ZN5boost23basic_wrap_stringstreamIcE3strB5cxx11Ev]+0x1b): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::str() const'
test_gpusim.cpp:(.text._ZN5boost23basic_wrap_stringstreamIcE3strB5cxx11Ev[_ZN5boost23basic_wrap_stringstreamIcE3strB5cxx11Ev]+0x35): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)'
test_gpusim.cpp:(.text._ZN5boost23basic_wrap_stringstreamIcE3strB5cxx11Ev[_ZN5boost23basic_wrap_stringstreamIcE3strB5cxx11Ev]+0x41): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
CMakeFiles/test_gpusim.dir/test_gpusim.cpp.o: In function `boost::unit_test::basic_cstring<char const>::basic_cstring(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
test_gpusim.cpp:(.text._ZN5boost9unit_test13basic_cstringIKcEC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN5boost9unit_test13basic_cstringIKcEC5ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x19): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
test_gpusim.cpp:(.text._ZN5boost9unit_test13basic_cstringIKcEC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN5boost9unit_test13basic_cstringIKcEC5ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x36): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::size() const'
CMakeFiles/test_gpusim.dir/test_gpusim.cpp.o: In function `void boost::unit_test::assign_op<char, char const>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, boost::unit_test::basic_cstring<char const>, int)':
test_gpusim.cpp:(.text._ZN5boost9unit_test9assign_opIcKcEEvRNSt7__cxx1112basic_stringIT_St11char_traitsIS5_ESaIS5_EEENS0_13basic_cstringIT0_EEi[_ZN5boost9unit_test9assign_opIcKcEEvRNSt7__cxx1112basic_stringIT_St11char_traitsIS5_ESaIS5_EEENS0_13basic_cstringIT0_EEi]+0x40): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*, unsigned long)'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `VTT for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long, unsigned long) const'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_erase(unsigned long, unsigned long)'
/home/user/progs/boost/boost/stage/lib/libboost_timer.so.1.68.0: undefined reference to `std::_V2::error_category::~error_category()'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char, unsigned long) const'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const'
/home/user/progs/boost/boost/stage/lib/libboost_timer.so.1.68.0: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_not_of(char, unsigned long) const'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `typeinfo for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >'
/home/user/progs/boost/boost/stage/lib/libboost_timer.so.1.68.0: undefined reference to `typeinfo for std::_V2::error_category'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*)'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::runtime_error::runtime_error(char const*)'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `vtable for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `operator delete(void*, unsigned long)'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `vtable for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::replace(unsigned long, unsigned long, char const*, unsigned long)'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/user/progs/boost/boost/stage/lib/libboost_timer.so.1.68.0: undefined reference to `vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char, unsigned long) const'
/home/user/progs/boost/boost/stage/lib/libboost_timer.so.1.68.0: undefined reference to `std::_V2::generic_category()'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_istringstream()'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/user/progs/boost/boost/stage/lib/libboost_timer.so.1.68.0: undefined reference to `std::_V2::error_category::_M_message[abi:cxx11](int) const'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct(unsigned long, char)'
/home/user/progs/boost/boost/stage/lib/libboost_unit_test_framework.so: undefined reference to `std::runtime_error::runtime_error(char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [test/test_gpusim] Error 1
make[1]: *** [test/CMakeFiles/test_gpusim.dir/all] Error 2
make: *** [all] Error 2

**Comment by lorton** [comment]
It's really hard for me to debug since I can't reproduce, but you could try going through test_gpusim.cpp and replace any bare "this is a string" with std::string("this is a string") -- looking at the link errors I think they're likely all around some weird non-auto-casting from char* -> std:string.

Asking again - do you have any custom defined CFLAGS or CXXFLAGS?  Also - which version of cuda sdk do you have installed?

**Comment by poganyp** [comment]
No, I do not use any flags. The CUDA might be the issue, since this is the only one part which I did not reinstall. But why were you thinking about this. All the errors point to Boost. I will try to install a newer CUDA.

**Comment by lorton** [comment]
@poganyp - I suspect the compiler or the flags are the problem, and Cuda is part of the compilation process (nvcc interacts with gcc).  I doubt it's any problem with the use of boost, GPUSim uses basic extremely common functionality.
