### ISSUE TITLE
Structure fingerprint not matching

### ISSUE THREAD

**Issue by lorton** [schrodinger/gpusimilarity#43]
For some reason ZINC92580503 (`CCCc1c2c(n(n1)C)n(c(n2)N)c3ccccc3`) isn't matching against a current build of the database using default settings (Morgan fingerprint) - it's only coming back as a 68% match.

Through a good deal of testing, this seems to be quite rare or entirely unique to this compound, but it is very worrisome.

**Comment by lorton** [comment]
@greglandrum - do you have any ideas here?  Does this molecule look like anything that Morgan might not be 100% consistent with?

**Comment by lorton** [comment]
Nevermind, testing against the newest version of gpusim works.  Might have been a bug fixed in the major rewrite a few months ago.

**Comment by greglandrum** [comment]
Glad you found that; it would have been quite scary
