### ISSUE TITLE
Can't get results for search query

### ISSUE THREAD

**Issue by Mariewelt** [schrodinger/gpusimilarity#59]
Hello,

I'm trying to launch gpusimilarity server through pre-built docker image. I'm able to create database and launch the server, but when I submit query I see no results in browser and the following message in the terminal:

```
Processing request 112620330
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QNativeSocketEngine(0x2c7d610), parent's thread is QThread(0x2696c80), current thread is QThread(0x7f4c74016f40)
QSocketNotifier: Can only be used with threads started with QThread
Unknown database  "default"  requested.
Search completed, time elapsed: 0
```

I would appreciate any ideas on why this is happening and how to fix it. 

Thanks!

**Comment by lorton** [comment]
Hi @Mariewelt - it looks to me like you're starting with a database not named `default.fsim`, but you're performing a search against a database named `default`, which is looking for `default.fsim`.  You could rename your fsim file to default, or adjust your search command to search against your fsim file name(s).

**Comment by Mariewelt** [comment]
Thanks @lorton, it saved the problem. Another minor thing I noticed is that pillow package not installed inside prebuilt docker image.

**Comment by lorton** [comment]
Thanks @Mariewelt - I've never tested the RDKit rendering engine using Docker I don't think.  If you fixed it on your local build feel free to submit a pull request, happy to have contributors of any size of code :)
